spring:
  application:
    name: employee-consumer
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/api-jva-users
    username: postgres
    password: 3005
    driver-class-name: org.postgresql.Driver
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
